### ISSUE TITLE
Option for brightness sensor

### ISSUE THREAD

**Issue by cd-FileX** [Reminimalism/MaterialsLiveWallpaper#2]
It would be pretty cool if there would be an option that the light brightness would be depending on the brightness sensor.

**Comment by pragma-once** [comment]
That's a cool idea, I'll see what I can do.

**Comment by pragma-once** [comment]
Added the option in v1.5. It will take some time (I think about 1 week) to be available on F-Droid.

**Comment by cd-FileX** [comment]
That's honestly great. It makes it look like the wallpaper would really exist.
Thanks for the implementation.
